### ISSUE TITLE
Error: setBroadcast EBADF on node v0.10.26

### ISSUE THREAD

**Issue by edasque** [grantmd/node-tivo#1]
Any idea what could cause this:

```
Creating config file...
We are: xxx
Our beacon: tivoconnect=1
method=broadcast
platform=pc/node.js
machine=A node.js server
identity=06e2b9e5-2848-4cf3-84b0-b73f6baef1de
services=TiVoMediaServer:8080/http

dgram.js:348
    throw errnoException(process._errno, 'setBroadcast');
          ^
Error: setBroadcast EBADF
    at errnoException (dgram.js:457:11)
    at Socket.setBroadcast (dgram.js:348:11)
    at Object.<anonymous> (/private/tmp/node-tivo/server.js:223:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by edasque** [comment]
still happens on node v0.10.33. @grantmd , any idea?

**Comment by edasque** [comment]
"Fixed" it by changing the code to `discovery.bind(config.tivo_port, function() {discovery.setBroadcast(true)});
` but it doesn't actually do anything but listing the Tivos on my network, right? There is no API to control them or anything like that.

**Comment by bjdraw** [comment]
Thanks for the fix. Worked for me too.
